#############################################################################
# Makefile for building: groundstation
# Generated by qmake (2.01a) (Qt 4.8.1) on: Sat Apr 20 00:13:47 2013
# Project:  groundstation.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile groundstation.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSvg -I/usr/include/qt4 -I/usr/lib/qt4/examples/designer/qledplugin -I/opt/ros/fuerte/include/opencv2 -I/opt/ros/fuerte/include/opencv -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L/home/justyna/Pulpit/groundstation2.0/../../../../usr/lib/x86_64-linux-gnu/qt4/plugins/designer/ -lqledplugin -L/home/justyna/Pulpit/groundstation2.0/../../../../opt/ros/fuerte/lib/ -lopencv_core -lopencv_calib3d -lopencv_highgui -lopencv_imgproc -lQtSvg -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		Robot.cpp \
		Arm.cpp \
		Cylinder.cpp \
		Engine.cpp \
		IDiggingSystem.cpp \
		IDrivingSystem.cpp \
		drawArrow.cpp \
		scada.cpp \
		battery.cpp \
		sciaga.cpp moc_mainwindow.cpp \
		moc_Robot.cpp \
		moc_IDiggingSystem.cpp \
		moc_scada.cpp \
		moc_battery.cpp \
		moc_sciaga.cpp \
		qrc_src.cpp
OBJECTS       = main.o \
		mainwindow.o \
		Robot.o \
		Arm.o \
		Cylinder.o \
		Engine.o \
		IDiggingSystem.o \
		IDrivingSystem.o \
		drawArrow.o \
		scada.o \
		battery.o \
		sciaga.o \
		moc_mainwindow.o \
		moc_Robot.o \
		moc_IDiggingSystem.o \
		moc_scada.o \
		moc_battery.o \
		moc_sciaga.o \
		qrc_src.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		groundstation.pro
QMAKE_TARGET  = groundstation
DESTDIR       = 
TARGET        = groundstation

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_scada.h ui_sciaga.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: groundstation.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtSvg.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtNetwork.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile groundstation.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtSvg.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtNetwork.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile groundstation.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/groundstation1.0.0 || $(MKDIR) .tmp/groundstation1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/groundstation1.0.0/ && $(COPY_FILE) --parents mainwindow.h Robot.h Arm.h Cylinder.h Engine.h IDiggingSystem.h IDrivingSystem.h Wheel.h drawArrow.h scada.h battery.h sciaga.h .tmp/groundstation1.0.0/ && $(COPY_FILE) --parents src.qrc .tmp/groundstation1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp Robot.cpp Arm.cpp Cylinder.cpp Engine.cpp IDiggingSystem.cpp IDrivingSystem.cpp drawArrow.cpp scada.cpp battery.cpp sciaga.cpp .tmp/groundstation1.0.0/ && $(COPY_FILE) --parents mainwindow.ui scada.ui sciaga.ui .tmp/groundstation1.0.0/ && (cd `dirname .tmp/groundstation1.0.0` && $(TAR) groundstation1.0.0.tar groundstation1.0.0 && $(COMPRESS) groundstation1.0.0.tar) && $(MOVE) `dirname .tmp/groundstation1.0.0`/groundstation1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/groundstation1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_Robot.cpp moc_IDiggingSystem.cpp moc_scada.cpp moc_battery.cpp moc_sciaga.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_Robot.cpp moc_IDiggingSystem.cpp moc_scada.cpp moc_battery.cpp moc_sciaga.cpp
moc_mainwindow.cpp: Robot.h \
		IDiggingSystem.h \
		Cylinder.h \
		Engine.h \
		Arm.h \
		IDrivingSystem.h \
		Wheel.h \
		battery.h \
		drawArrow.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_Robot.cpp: IDiggingSystem.h \
		Cylinder.h \
		Engine.h \
		Arm.h \
		IDrivingSystem.h \
		Wheel.h \
		battery.h \
		Robot.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Robot.h -o moc_Robot.cpp

moc_IDiggingSystem.cpp: Cylinder.h \
		Engine.h \
		Arm.h \
		IDiggingSystem.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) IDiggingSystem.h -o moc_IDiggingSystem.cpp

moc_scada.cpp: ui_scada.h \
		drawArrow.h \
		Robot.h \
		IDiggingSystem.h \
		Cylinder.h \
		Engine.h \
		Arm.h \
		IDrivingSystem.h \
		Wheel.h \
		battery.h \
		scada.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) scada.h -o moc_scada.cpp

moc_battery.cpp: battery.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) battery.h -o moc_battery.cpp

moc_sciaga.cpp: sciaga.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) sciaga.h -o moc_sciaga.cpp

compiler_rcc_make_all: qrc_src.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_src.cpp
qrc_src.cpp: src.qrc \
		images/bok.png \
		images/small.png \
		images/dol.png \
		images/small.pic \
		images/map.png
	/usr/bin/rcc -name src src.qrc -o qrc_src.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_scada.h ui_sciaga.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_scada.h ui_sciaga.h
ui_mainwindow.h: mainwindow.ui \
		qled.h
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

ui_scada.h: scada.ui
	/usr/bin/uic-qt4 scada.ui -o ui_scada.h

ui_sciaga.h: sciaga.ui
	/usr/bin/uic-qt4 sciaga.ui -o ui_sciaga.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		Robot.h \
		IDiggingSystem.h \
		Cylinder.h \
		Engine.h \
		Arm.h \
		IDrivingSystem.h \
		Wheel.h \
		battery.h \
		drawArrow.h \
		scada.h \
		ui_scada.h \
		sciaga.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		Robot.h \
		IDiggingSystem.h \
		Cylinder.h \
		Engine.h \
		Arm.h \
		IDrivingSystem.h \
		Wheel.h \
		battery.h \
		drawArrow.h \
		ui_mainwindow.h \
		qled.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

Robot.o: Robot.cpp Robot.h \
		IDiggingSystem.h \
		Cylinder.h \
		Engine.h \
		Arm.h \
		IDrivingSystem.h \
		Wheel.h \
		battery.h \
		drawArrow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Robot.o Robot.cpp

Arm.o: Arm.cpp Arm.h \
		Engine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Arm.o Arm.cpp

Cylinder.o: Cylinder.cpp Cylinder.h \
		Engine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Cylinder.o Cylinder.cpp

Engine.o: Engine.cpp Engine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Engine.o Engine.cpp

IDiggingSystem.o: IDiggingSystem.cpp IDiggingSystem.h \
		Cylinder.h \
		Engine.h \
		Arm.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o IDiggingSystem.o IDiggingSystem.cpp

IDrivingSystem.o: IDrivingSystem.cpp IDrivingSystem.h \
		Wheel.h \
		Engine.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o IDrivingSystem.o IDrivingSystem.cpp

drawArrow.o: drawArrow.cpp drawArrow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o drawArrow.o drawArrow.cpp

scada.o: scada.cpp scada.h \
		ui_scada.h \
		drawArrow.h \
		Robot.h \
		IDiggingSystem.h \
		Cylinder.h \
		Engine.h \
		Arm.h \
		IDrivingSystem.h \
		Wheel.h \
		battery.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scada.o scada.cpp

battery.o: battery.cpp battery.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o battery.o battery.cpp

sciaga.o: sciaga.cpp sciaga.h \
		ui_sciaga.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sciaga.o sciaga.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_Robot.o: moc_Robot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Robot.o moc_Robot.cpp

moc_IDiggingSystem.o: moc_IDiggingSystem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_IDiggingSystem.o moc_IDiggingSystem.cpp

moc_scada.o: moc_scada.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_scada.o moc_scada.cpp

moc_battery.o: moc_battery.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_battery.o moc_battery.cpp

moc_sciaga.o: moc_sciaga.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sciaga.o moc_sciaga.cpp

qrc_src.o: qrc_src.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_src.o qrc_src.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

